import { Raleway } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Mysql',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        <div className='h-[calc(100vh-5rem)]'>{children}</div>
      </body>
    </html>
  )
}
